//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRental
    {
        public int id { get; set; }
        public string costumerName { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<System.DateTime> rentDate { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public int carType { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
